### ISSUE TITLE
El737 Counter Simulation stop feature

### ISSUE THREAD

**Issue by nikhilbiyani** [ess-dmsc/sinq-amorsim#3]
When the user issues stop command, the measurement should only be sopped and when the connection closes the event generation should stop.

**Comment by michele-brambilla** [comment]
If I'm not wrong this should correspond to the "pause" command. Can't we use that?

**Comment by michele-brambilla** [comment]
As we discussed with Mark, I'll spit the stop command into a "stop" that will interrupt data transmission and "exit" that will kill the process
